---
- hosts: all
  vars:
    container_pilot_version: 3.8.0
    flask_version: 1.0.3
  tasks:
    - name: Install flask
      pip:
        name: "flask=={{ flask_version }}"
        state: latest

    - name: Create app directory
      file:
        path: /app
        state: directory
        mode: '0755'

    - name: Download python script for server
      get_url:
        url: "https://raw.githubusercontent.com/ozlevka/syte-task/master/server/server.py"
        dest: /app
